### ISSUE TITLE
Annotation option should automatically be disabled when not available

### ISSUE THREAD

**Issue by bradenhutch** [BYU-ODH/yvideo-client#10]
Right now, the option to enable annotations does not disappear when there are no annotations available. It should disappear automatically when the last annotation track is deleted. 

![noannotations](https://cloud.githubusercontent.com/assets/22623998/22342596/26384632-e3b2-11e6-94d6-d118b0b8ddcd.JPG)

**Comment by clevergrant** [comment]
Taken care of in the new implementation on the new UI
