### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by JKJensen** [BYU-ODH/yvideo-client#11]
This is where I'll be making notes on colors and other aspects of the new site as part of our style guide:

In general:
No gradients, and no drop shadows. Aiming for a "flat design"

**Colors:** ([Viewable here](https://color.adobe.com/Y-Video-Color-Scheme-color-theme-8776809/))
Red: #E7495F
Hover Red: #CD4155
Blue: #2788B6
Hover Blue: #22759C
Yellow: #EBE561
Hover Yellow: #D1CC56
Topbar Gray: #595959
BackgroundGray: #373737

**Misc. Colors for user logins:**
Blue: #1693BF
Green: #0EA47A
Purple: #7A4579
Brown: #543A3A
Dirty Red: #D56073
Orange: #EC9E69

**Font:**
Source Sans Pro

Logo:
1000px:
![y-videologo-1000px](https://cloud.githubusercontent.com/assets/5481718/19661701/fb10e432-99f1-11e6-8581-cc7407405a0a.png)
32px FavIcon:
![y-videologo-retinafavicon](https://cloud.githubusercontent.com/assets/5481718/19661700/fb1017fa-99f1-11e6-8289-0381030afb78.png)

**Comment by clevergrant** [comment]
Closing this because of the Figma file taking care of this
