### ISSUE TITLE
Redesigned Y-Video Player Proposal

### ISSUE THREAD

**Issue by JKJensen** [BYU-ODH/yvideo-client#12]
![videoplayerwithtranscript](https://cloud.githubusercontent.com/assets/5481718/21555633/5d38d20c-cddf-11e6-9689-7cb6100db5b0.png)
[Example Video](https://youtu.be/pqKIS--Hpig)

When not at full screen, the Y-Video Player is 1280px tall by 540px wide. This includes both the video itself and a 320px wide sidebar.

When a user first enters the page, there should be a black overlay (50% opacity) covering the thumbnail image, along with a large play button in the center of the video portion.

The Transcript pane should not be obscured, and will be on by default, with the pin button activated in dark gray (595959) . The transcript pane displays unless there are no subtitles, or the content creator has disabled them.

Clicking anywhere on the video player (not the transcript pane), triggers the start of the video.

## Button explanations:
**Play button** | [fa-play](http://fontawesome.io/icon/play/) | Hover: Start the video (Spacebar)
Pause button [fa-pause](http://fontawesome.io/icon/pause/) | Hover: Stop the video (Spacebar)
The play button will exchange with the pause button.
Anytime the video is playing the pause button should appear in the bottom left corner. While the video is paused, the entire play bar should pop up and stay up, with the play button in the bottom left corner. The spacebar button toggles play/pause.

**Previous Line** | [fa-step-backward](http://fontawesome.io/icon/step-backward/)| Hover: Go to last subtitle (Left Arrow Key)
The Previous Line button will return users to the previous subtitle. If pressed more than half a second after the current subtitle has started, will repeat the current subtitle.

**Next Line** | [fa-step-forward](http://fontawesome.io/icon/step-forward/)| Hover: Go to next subtitle (Left Arrow Key)
The Next Line button will advance users to the next subtitle.

**Volume** | [fa-volume-up](http://fontawesome.io/icon/volume-up/) | Hover: Change the volume ( Up arrow/Down arrow )
Opens a small volume change subwindow with a sliding bar. While the submenu is open, there is gray (#666666, opacity 50%) indicator behind the volume icon denoting that the icon is active.
The subwindow is light gray (#DDDDDD), and a has a drop shadow (Color: 333333, Opacity: 50%, Y-Offset: 5px, X-Offset: None, Blur: 5px)
Hovering outside of the subwindow for more than 1/4 of a second causes the subwindow to slide back down.
At 89-100% volume use: [fa-volume-up](http://fontawesome.io/icon/volume-up/)
At 1-89% volume use: [fa-volume-down](http://fontawesome.io/icon/volume-down/)
At 0, or muted use: See attached custom made icon pack file [Y-Video-MuteIcon.png](https://cloud.githubusercontent.com/assets/5481718/21556458/1ba9c628-cde6-11e6-8845-ba770ffd3440.png)
When the brackets are used as a shortcut for changing the volume, do not bring up the entire play bar menu, only bring the volume icon/gray indicator and the volume submenu. ([Rough example](https://i.gyazo.com/1f856c76b2936d5b1392d48139be37d2.gif)) Brackets change the volume in 10% increments. Holding ctrl (and/or shift) plus a bracket changes the volume in 1% increments.
If a user clicks the volume icon, the volume mutes. Clicking the volume icon again reverses the volume back to where it was before.
Clicking the "m" key will also mute/unmute. 

<img width="638" alt="screenshot 2016-12-29 17 18 06" src="https://cloud.githubusercontent.com/assets/5481718/21556921/ce2566b4-cdea-11e6-87a1-b1963935a37a.png">

**Adjust Speed** | [fa-tachometer](http://fontawesome.io/icon/tachometer/) | Hover: Change the speed of the video (Bracket Keys [ and ] )
Opens a small speed adjust subwindow with a sliding bar. Normal is the default. Using the bracket keys to adjust increases or decreases the speed by .25x speed.
The submenu and the gray indicator look and behave similarly to the volume submenu.

![turningoffsubtitley-video](https://cloud.githubusercontent.com/assets/5481718/21569562/86737bb4-ce83-11e6-9bf8-2a0b2a301d15.gif)

**CC icon** | [fa-cc](http://fontawesome.io/icon/cc/)| Hover: Turn on/off subtitles (Number keys 1-9)
Clicking the CC icon turns off/on subtitles. Clicking a highlighted language will stop that language from displaying. Clicking on the triangle will open a subwindow like this:
<img width="521" alt="screenshot 2016-12-30 11 37 03" src="https://cloud.githubusercontent.com/assets/5481718/21569648/67e8452a-ce84-11e6-8989-52befd8c13a4.png">
The number keys correspond to the order of the languages in the language select box. For the above example, English would be 1, Spanish 2, Japanese-Romaji 3, Japanese-Kanji 4. So pressing 1 on the keyboard (or number pad) will toggle English subtitles on and off. Pressing 2 would toggle Spanish on/off. There are no keyboard shortcuts for languages beyond the first 9.
Pressing 0 is the same as hitting the CC icon: it turns off all subtitles if the subtitles are active (getting rid of the indicator [like this](https://cloud.githubusercontent.com/assets/5481718/21569808/d50b6b72-ce85-11e6-8bfe-acf1a802b5d6.png)). And clicking the CC icon/Number 0 turns on the last displayed subtitles.
Note: Subtitles are on by default in Y-Video. Which ones depends on the settings the teacher/TA has set.
Subtitles that have names beyond the language itself are truncated to the three letter code of the language and up to 8 characters (Which is about how much space we have when [using wide unicode characters](https://cloud.githubusercontent.com/assets/5481718/21570078/47aa79f0-ce88-11e6-889b-32f4328a9e1f.png).)
The language select submenu shows the entirety of the subtitle name. More than 15 subtitle tracks will split the tracks into columns of 15 each. More than 45 languages causes the submenu to have a large arrow on the right to go to a next page for language selection.
The default displayed languages in the player bar will be the top two languages inputted in the system first (or set by the teacher). However, any active languages that are on will supercede this.

For example:
Starting with English subtitles on and Spanish subtitles off:
<img width="291" alt="screenshot 2016-12-30 12 31 10" src="https://cloud.githubusercontent.com/assets/5481718/21570467/ec350c9e-ce8b-11e6-9bc4-4b3f60341cf3.png">
User clicks the triangle and turns on Japanese-Romaji. The two languages displayed in the player bar will be English and Jpn-Romaji.
<img width="295" alt="screenshot 2016-12-30 12 29 43" src="https://cloud.githubusercontent.com/assets/5481718/21570468/f0289532-ce8b-11e6-87fc-37775840e6ea.png">
If the user clicks on Jpn-Romaji, those subtitles will turn off. However in the player bar Jpn-Romaji will stay there for the duration of the session.
<img width="315" alt="screenshot 2016-12-30 12 30 16" src="https://cloud.githubusercontent.com/assets/5481718/21570471/f6ce5714-ce8b-11e6-9d7e-487555be866d.png">
For keyboard shortcuts, numbers 1 and 2 are always the first two languages displayed in the player bar. The other languages are exchanged for whichever language was replaced. So in the above example the keyboard shortcuts would become English 1, Jpn-Romaji 2, Spanish 3, Japanese-Kanji 4.
Refreshing the page will revert the subtitles back to the defaults the teacher set.

<img width="1002" alt="screenshot 2016-12-30 13 16 37" src="https://cloud.githubusercontent.com/assets/5481718/21571217/c1c04da0-ce92-11e6-9ca4-5729c561064a.png">

**Annotation icon** | [fa-comment-o](http://fontawesome.io/icon/comment-o/) | Hover: Turn on/off Annotations (SHIFT+Numbers 1-9)
Teachers can make as many annotation tracks as they like, however, only the first six get distinct highlight colors, after that the colors rotate in order.

When the sidebar is in dark mode, the colors of both the subtitle annotations and the transcript annotations are the same. When the sidebar is in light mode, the colors of the subtitles correspond to a darker shade of a similar color in the transcript pane. 

Light Shade, Dark Shade
Red: FF6A7F, E7495F
Orange: FFB347, BF8635
Green: 15F0B3, 0EA47A
Pink: FF90FD, 7A4579
Brown: D2B48C, 564A39
Yellow: EBE561, 6B692C

Annotated words appear in the sidebar bolded.
<img width="827" alt="screenshot 2016-12-30 13 34 43" src="https://cloud.githubusercontent.com/assets/5481718/21571411/c600c6c2-ce94-11e6-92d4-7231f308da91.png">
An active annotation area will have colored highlights corresponding to the annotation color.

The numbers/keyboard shortcuts for annotations are fixed and do not rearrange like on the caption menu. So having two annotation tracks on could look like this:
<img width="1086" alt="screenshot 2016-12-30 13 38 18" src="https://cloud.githubusercontent.com/assets/5481718/21571451/4103ce14-ce95-11e6-9dc3-733e4ea062ca.png">

Pressing Shift+A number 1-9 will toggle that annotation track.
Annotation tracks are also default on if the professor sets them that way.

**Time Indicator** will display the current time over the full time of the video.

![fullscreenmode](https://cloud.githubusercontent.com/assets/5481718/21573096/38c7d6c6-cea6-11e6-99d1-0b99c3872b00.png)

**Fullscreen** | [fa-arrows-alt](http://fontawesome.io/icon/arrows-alt/) | Hover: Fullscreen mode (F)
**Normal View** | [fa-compress](http://fontawesome.io/icon/compress/) | Hover: Revert to normal view (Escape or F)
An indicator appears on the compressor icon when in full screen. 

**Pin** | [fa-thumb-tack](http://fontawesome.io/icon/thumb-tack/) rotated 45 degress | Hover: Unpin the transcript pane (P)
While the pin is not active, hovering over the pin icon says: "Pin the transcript pane."
The pin is default on.

**Language select** 
[Gif Example](https://gyazo.com/6ec4517a592c1b5d6c7b8e770413ec67)
A user clicks on the language select box and brings up the language they want. Only one language is displayed at a time in the annotation sidebar. When a language is selected, a corresponding subtitle is turned on (and no previous subtitles are turned off).

**Anchor** | [fa-anchor](http://fontawesome.io/icon/anchor/) | Hover: Anchor transcript to current location (A)
Does exactly as the previous version did. Keeps the transcript scrolling when the subtitle changes.
Default on.

![turningondarkmode](https://cloud.githubusercontent.com/assets/5481718/21572269/e1524362-ce9c-11e6-8223-739f5fdcc89a.gif)

**Dark Mode** | Attached .zip of custom icons moon.png | Hover: Dark Mode (D)
**Light Mode** | Attached .zip of custom icons sun.png | Hover: Light Mode (D)
Light mode colors | Dark Mode colors
Background: DDDDDD | 222222
Text: 000000 | CCCCCC
Clicking that icon toggles the light and dark modes and changes the icon as well.
Keep in mind that annotation colors change depending on which mode the transcript is in.

**Transcript Tab** | Hover: View the transcript (T) Pin to keep transcript open (P)
This only appears when the transcript pane is unpinned AND a user is moving their mouse over the subtitles/video player.

Hovering in this area above the dividing line (that's not a button) triggers a help hover that says: Use Ctrl/⌘+F to search this transcript.

![y-video-definitionstab](https://cloud.githubusercontent.com/assets/5481718/21572711/f5ff3310-cea1-11e6-9abe-e58332b42f15.png)

**Definitions Tab**| Hover: Definitions for hovered words will display in this tab
This pane behaves similarly to the definitions pane on the old Ayamel site.
Except that now when users hover over a word it will translate in 1 second. During that 1 second interval the word will stay it's same color until the 1/4 second mark, which it will then transition to blue. 72D2FC for words that were light. 2788B6 for words that were dark.
Once that happens, (if the transcript pane is closed) the transcript pane will slide out with the definition pane open.
If the transcript pane is open already, the definition pane will slide open in a tenth of a second.
Replace the "Add to word list" button with "Add to Notes."
The user can hover over the transcript pane OR the captions in order to get a definition.

Words that are annotated take longer to get the definition for. They stay the same color until the 3/4 second mark, and then turn blue and the definition shows up at the 1.5 second mark. (These exact times will need to be user tested once we have a working model)

![y-video-annotationsclickonhighlightedwords](https://cloud.githubusercontent.com/assets/5481718/21572712/05f2343e-cea2-11e6-878b-688a2dd9519c.png)

**Annotations Tab** | Hover: Clicked on Annotations will display in this tab
This pane behaves similarly to the annotations pane on the old Ayamel site, and the definitions tab described above.
<img width="265" alt="screenshot 2016-12-30 15 21 47" src="https://cloud.githubusercontent.com/assets/5481718/21572857/bbc79fbe-cea3-11e6-9159-0bac879cb519.png">

At the end of each annotation there is an "Add to Notes" button that adds the text of the annotation to the notes list.

------

[CustomIconPack](https://github.com/BYU-ODH/Ayamel/files/679261/Y-VideoCustomIcons.zip) (Keep in mind these icons are white, so they will not show up on a white background)

**Comment by reynoldsnlp** [comment]
if there are any ideas that we like here, we can make separate issues, otherwise I think we abandon this issue.
