### ISSUE TITLE
Creating international cinema 

### ISSUE THREAD

**Issue by saejong-jang-by** [BYU-ODH/yvideo-client#127]
- public only for BYU student and faculty members

- handles collections which are studio films with copyright

- similar features like public collection

**Comment by youthrich40** [comment]
We decided to keep this feature in the public collection. Collection now has two additional params `copyrighted` and `public`. If the collection is public=true, copyrighted=false, then it is public for anyone without login. However, the collection is public=true, copyrighted=true, then only BYU users can access this collection.
