### ISSUE TITLE
Redesigned Content Settings Proposal

### ISSUE THREAD

**Issue by JKJensen** [BYU-ODH/yvideo-client#13]
[Invision page](https://invis.io/QW9IAKAY5#/212820628_Teacher_-_Video_Title_-_Main)

This redesign is aimed at making it more difficult to disable aspects of Y-Video, while making it very easy for the default option to be the most preferred.

------
Captions menu:

<img width="1108" alt="screenshot 2016-12-30 19 25 17" src="https://cloud.githubusercontent.com/assets/5481718/21575046/be879f98-cec5-11e6-96a2-28687d4a1e05.png">

When a user uploads a caption file and selects a language, the track name box automatically fills in the name of the track as the language name. The user can then add up to eighty characters after that. Parse the user input so that you remove the language they entered, and set anything else they added (minus the first " " or "-") as the Track Name.
So if a user selected the language "English," and then the track name was "English-Grammar," the track name would be "Grammar."
But if a user selects the language "Japanese," and sets the track name as "English-Grammar," the track name would be "English-Grammar."

Any Captions uploaded are default enabled. The first caption track a user uploads on a single piece of content is enabled and set as default. 

If a user tries to exit away from this menu and no subtitles are set as default, pop up a warning modal. "Default subtitle required. [1st Caption Track Name] will be set as default. If you don't want subtitles, please disable all subtitle tracks."

**Hover dialogue:**

**Create/Edit tracks in CaptionAider** | Open our caption editor in order to edit subtitle text and timings

**Choose file** | Select a subtitle file on your computer, we accept .vtt .srt .stl .ssa .ttml and .sbv

**Select Language** | Select the language that your subtitle is in

**Track Name** | Set the name of the track, leave blank unless desired

**Kind** | Specify the kind of caption track, for most purposes please use "Subtitles"

**Upload** | Upload your subtitle file into Y-Video

**Enabled Check Boxes** | If you are still editing your subtitles, you can uncheck this box

**Default** | These subtitles will be on by default when others view this content

**Edit** | Edit these subtitles in CaptionAider

**Download** | Download subtitles to your computer

**Delete** | Delete subtitles

------
Set Restrictions:

<img width="705" alt="screenshot 2016-12-30 19 53 47" src="https://cloud.githubusercontent.com/assets/5481718/21575164/b8a52682-cec9-11e6-92cb-92b5cb880da3.png">

The main purpose of the current Configurations menu on Ayamel is to restrict access to content. That is how everything is by default. Y-Video is set up so that everything is ON by default unless teachers/TA's actively disable them.

**Hover dialogue:**

**Restrict language translation to only** | Disable the ability for students to pick which language their definitions are translated into. By default the only language they can view definitions in, will be the one you pick.

**Disable automatic definitions** | Prevent students from viewing definitions

**Disable transcript pane** | Prevent students from viewing the transcript of the video

**Comment by clevergrant** [comment]
Closing because it's irrelevant now
