### ISSUE TITLE
Login Sequence & react-router-dom interaction

### ISSUE THREAD

**Issue by clevergrant** [BYU-ODH/yvideo-client#16]
The issue with react-router-dom is that we can't figure out a way to automatically log clients in when navigating to a page except by a weird use of renderProps. Not sure if it's the right way to go, so I'm in contact with the guy who co-wrote react-router to find out what the issue is with using an external URL for a redirect instead of redirecting to a different component.

**Comment by verdude** [comment]
Also, could we do something like this:

```
if (Cookies.get('auth') !== 'true') {
    window.location.href = 'https://ayamelbeta.byu.edu/auth/cas/redirect' + window.location.origin + Path
    return <Error toggleLost={function(){}} error='302' message={'Logging  you in...'} />
} else { ... }
```

It looks a little weird if we just render the string while we are redirecting.

**Comment by clevergrant** [comment]
I made it work a while ago, all good
