### ISSUE TITLE
Issues in Content

### ISSUE THREAD

**Issue by saejong-jang-by** [BYU-ODH/yvideo-client#211]
- new user gets 403 for creating content.
- Creating content, description should be optional.
- The content title has to be optional or takes resource title as default.
- Get 403 from creating content with the resource should display feedback.

**Comment by anita908** [comment]
- [ ] new user gets 403 for creating content.
- [ ] Creating content, description should be optional.
- [ ] The content title has to be optional or takes resource title as default.
- [ ] Get 403 from creating content with the resource should display feedback.
