### ISSUE TITLE
Create a way to identify all videos or files within a resource

### ISSUE THREAD

**Issue by esdraszx** [BYU-ODH/yvideo-client#299]
If a resource has more than one file or video, the user needs to be able to identify them. 
Let the user input a user given title to identify a file within a resource.

**Comment by youthrich40** [comment]
- When uploading the file, it requires a filename as an identifier.
- When creating content from the resource, the user can identify the same target languages by identifier.

**Comment by youthrich40** [comment]
Issues currently have:
-  It looks like our backend searches file by the target language. We can consider searching file by fileId instead of the target language, so it can identify the same target language by fileId.

**Comment by esdraszx** [comment]
Closed. Already solved
