### ISSUE TITLE
Alphabetizing contents should ignore articles ('a', 'an', 'the')

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#318]
Something like this solution: https://stackoverflow.com/a/34347659/2903532

**Comment by anita908** [comment]
![Screen Shot 2022-02-09 at 10 39 48 PM](https://user-images.githubusercontent.com/55892347/153344690-cde4f6d9-befa-42de-b7b7-23e6eaa67962.png)

Fix!
