### ISSUE TITLE
Errors when teacher accesses collection manager

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#321]
This teacher was trying to access collection manager to add a course to the collection. The collection is owned by Russell Hansen, but the teacher has been added as a TA. I'm guessing this is connected to automatically capturing endpoint errors to give the user error messages.

> Hey, Rob.
> 
> Looks like I don’t have permissions to link the classes. The process is pretty intuitive, but I get the two error messages (aplenty) and eventually get the screen with the buttons grayed out.

![image](https://user-images.githubusercontent.com/13379223/151078411-1f820f24-7683-497d-b769-243399b3c80b.png)
![image](https://user-images.githubusercontent.com/13379223/151078509-403ea4fe-ef74-4f38-9d55-d1b7c690f4f3.png)
![image](https://user-images.githubusercontent.com/13379223/151078450-1c7cd6fc-bb49-4179-9cd5-23bf81176875.png)

**Comment by esdraszx** [comment]
Original issue is to let a TA add a course to a class. - Solved by changing the role-level permission in the back end for the specific endpoint

Other issues:

1. TA's can't access manage collections if they are only students (front-end issue) - in progress
2. TA's can't create content for a given collection - solved by changing role-level permission in the back back.
