### ISSUE TITLE
typo in course example

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#322]
In `src/components/c/CollectionPermissions/index.jsx`, the example `ENG` should be `ENGL`, and the word `Department` should probably be changed to `Dept - Ex: `.

**Comment by anita908** [comment]
![Screen Shot 2022-02-09 at 10 41 04 PM](https://user-images.githubusercontent.com/55892347/153344755-7b1c4113-fad6-4095-9341-81487c0ada22.png)

Fix!
