### ISSUE TITLE
when adding instructors to resource, you cannot delete a netid you added until you save your changes.

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#337]
If I add a netid, I should be able to delete it immediately (before clicking the `Save` button). However, currently you have to save first, then open the modal again to delete it.

**Comment by reynoldsnlp** [comment]
If you click on the delete button before it has been saved, it yields a `500` error. Deleting an unsaved netid shouldn't interact with the server at all.

**Comment by reynoldsnlp** [comment]
Actually, it just isn't updating on deletion. The `Cancel` and `Save` buttons are totally unnecessary since each netid is sent immediately.

**Comment by ChristianHall131** [comment]
in src/components/modals/components/ManageInstructors/index.js, inherits props from src/components/ManageResource/index.js
