### ISSUE TITLE
Add user modal should be keyboard-friendly

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#344]
[tab] and [enter]

**Comment by ChristianHall131** [comment]
It is functional, we just need css to highlight fields and buttons when active

**Comment by Thanatos55** [comment]
I'll go through and double check all other modals for the same visual issue, making sure that there's an outline for tabs and enter, and that they're blue.
Also looking for other look and feel issues on any of the modals along the way.
