### ISSUE TITLE
The translation and CC icons are always visible on manage collection page, regardless of whether they have translation or subtitles.

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#345]

**Comment by reynoldsnlp** [comment]
The `Captions` toggle should be gray if there are no subtitles, and the CC icon should be invisible.

**Comment by reynoldsnlp** [comment]
The translation toggle should be stuck off if the language of the content is not one of the supported languages.

**Comment by reynoldsnlp** [comment]
If someone tries to turn on one of these toggles, they should receive a message explaining why that is not possible.

**Comment by reynoldsnlp** [comment]
We probably need another endpoint for this (or expand the `collections` endpoint).

**Comment by ChristianHall131** [comment]
fixed with pull request, except for subtitles
