### ISSUE TITLE
Incomplete modal after trying to open a video in the player with tab left open overnight

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#374]
I left my tab open overnight, and when I tried to play a video, a modal came up with only a horizontal line, and something about `Go back`. I suspect it was the modal in `src/components/c/Error/index.jsx`.

This might be connected to an expired session id. The desired behavior is that if the session id expires, and any action fails because of a bad session id, the user should be shown a modal that says something like `"Your session has expired. Please log in again."` with only one button to `Log in`, which takes them back to the log-in page.

**Comment by dallan21** [comment]
@reynoldsnlp was the error message the one with all the raw HTML inside of it or was It an actual modal that shows up but doesn't fully render?

**Comment by dallan21** [comment]
I  believe this was solved with my fix on the back end @reynoldsnlp
