### ISSUE TITLE
If there are no subtitles for a content, the `CC` icon in the player should have different behavior

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#375]
Either...

1. ... make the `CC` icon inactive, and on hover, show a tooltip saying `No subtitles have been added for this video`...
1. ... or when the `CC` icon is clicked, display something like `No subtitles have been added for this video`.

**Comment by dallan21** [comment]
@reynoldsnlp So for this, if there are no closed captions then we don't want the CC icon to show up correct?
