### ISSUE TITLE
Automatic pauses in the player should show explicitly that the pause was automatic

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#378]
When a pause is initiated automatically by the instructor, a message or cue should be shown that makes it clear that the pause was automatic. Otherwise, the user can easily be confused about why the player stopped.

**Comment by reynoldsnlp** [comment]
The message should be shown on top of the video, with a `Close` button at the bottom-right corner. It's possible that the instructor would want the student to look at the image, so the player should not start playing again automatically after closing the message.

So the flow should be...

1. Player pauses automatically because of annotation
2. Message is immediately shown over player
3. User clicks `Close`
4. User clicks play button to continue

**Comment by Aaron-M-Anderson** [comment]
Closed by merge pull request #450
