### ISSUE TITLE
Add message option to the Pause annotation

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#379]
Give the instructor the option of showing a message at an automatic Pause event. If the message field is not empty, then when the automatic pause occurs, the message will be displayed.

**Comment by reynoldsnlp** [comment]
This issue could be integrated with #378.

**Comment by reynoldsnlp** [comment]
The annotations JSON would need a new field `"message"` (instead of `"end"`).

**Comment by Aaron-M-Anderson** [comment]
Closed by merge pull request #450
