### ISSUE TITLE
0 Content in collection, Tooltip Bug

### ISSUE THREAD

**Issue by Aaron-M-Anderson** [BYU-ODH/yvideo-client#380]
When there is no content in a collection, the tooltip will appear right in the middle of the add button, which makes it difficult to click on. Please ask Aaron for help with this one, he knows where you should mess around with it to find a solution, he just doesn't know the solution.

**Comment by dallan21** [comment]
@Aaron-M-Anderson I'm gonna take a look at this issue. Where should I mess around with the code in order to find that solution?
