### ISSUE TITLE
Event Listener Hotkey bug

### ISSUE THREAD

**Issue by Aaron-M-Anderson** [BYU-ODH/yvideo-client#381]
From line 329 down to about 387 there is a bug that has to do with the code that was written for the hotkeys for the video player. Basically, the listener continues to look for a key press even when the video container is closed and its wrapper should be closed as well. This causes a problem because any time that the video player is visited and left, the variables that the listener is looking for are gone, and so the next key press causes an error.

**Comment by Thanatos55** [comment]
I've gone ahead and commented out the code that was causing the issue on the new branch so that one can see what exactly is causing the issue and start working on it.
