### ISSUE TITLE
Videos are in wrong order

### ISSUE THREAD

**Issue by Aaron-M-Anderson** [BYU-ODH/yvideo-client#382]
It seems that the videos are displayed in different orders when I look at the collection on the homepage vs when I'm looking at the collection in Manage Collections. This was causing some confusion for me.
![Screenshot 2022-04-29 152942](https://user-images.githubusercontent.com/43586612/166064975-4af43bf9-d29a-4698-bdba-4c7ad090b3df.png)

![Screenshot 2022-04-29 153042](https://user-images.githubusercontent.com/43586612/166065154-511c956e-1f44-449e-9dff-f1eed82fa008.png)

**Comment by reynoldsnlp** [comment]
Good catch. Anywhere that videos are listed, they should be in alphabetical order, ignoring "a", "an", and "the".

**Comment by dallan21** [comment]
The collection items in collections are rendering them in alphabetical order. However, the one in manage collections just renders them right above the first collection item.
