### ISSUE TITLE
In "Create New Content" modal, all options in "Target Language" end in a colon

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#396]

**Comment by dallan21** [comment]
@reynoldsnlp I looked through manage collections and manage public collections and when I create new content the target languages don't have colons next to them. could you point me to the right place to find this issue?

**Comment by dallan21** [comment]
<img width="415" alt="Screen Shot 2022-05-05 at 11 51 11 AM" src="https://user-images.githubusercontent.com/90338790/166983101-b5c67984-e64d-4b07-8986-2be514b5f007.png">

**Comment by reynoldsnlp** [comment]
@dallan21 This one is done, right?

**Comment by dallan21** [comment]
@reynoldsnlp yes, this issue was completed about 2 weeks ago. Sorry, I just saw this
