### ISSUE TITLE
Git rid of files that aren't being used

### ISSUE THREAD

**Issue by ChristianHall131** [BYU-ODH/yvideo-client#421]
There are files, especially in the components, that are no longer used that need to be removed

**Comment by dallan21** [comment]
-EventControllerContainer (empty)
-Resource.js (everything is commented out)
-Settings.js (Everything is commented out)
-Events-> index.jsx (only has a p tag that is hidden **may or may not need**)
-VideoControls-> index.jsx (only has a style component that's empty)
** There may be more that are less apparent so im going to look into it more **

**Comment by jtabilot** [comment]
For the all the files mentioned above in the comments, after research the result is:

- EventControllerContainer (Empty File): Deleted in this commit. 
-Resource.js (everything is commented out) : **It is being used**. 
-Settings.js (Everything is commented out): **It is being used**. 
-Events-> index.jsx (only has a p tag that is hidden may or may not need): **It is being used by 10 diferent files**. 
-VideoControls-> index.jsx (only has a style component that's empty): Was deleted previously.
