### ISSUE TITLE
`PlayerControls` modals are finnicky

### ISSUE THREAD

**Issue by Aaron-M-Anderson** [BYU-ODH/yvideo-client#423]
The `onMouseLeave` event on the tooltips or modals that appear when one, for example, clicks on the `CC` icon, sometimes closes as the mouse is entering for the first time, and can only be remedied by moving the mouse a little slower.

**Comment by dallan21** [comment]
I've been going over all the buttons and the tooltips are working fine. Would you be able to show me what you mean? The only problem I see is when we resize the screen, the tool tips are not directly over the button anymore. They become offset to the left of the button. @Aaron-M-Anderson
