### ISSUE TITLE
subtitle add-buttons peeking out

### ISSUE THREAD

**Issue by Aaron-M-Anderson** [BYU-ODH/yvideo-client#425]
When the subtitle modal where you decide to start from scratch or upload a subtitle track, you can, for some reason, see the `+` buttons that are tangent to the fields where one can add a new subtitle or edit one to an already existing subtitle track. The buttons peek right through the grey-out wrapper that is meant to cover everything behind the modal.

**Comment by Aaron-M-Anderson** [comment]
![image](https://user-images.githubusercontent.com/43586612/167954741-37cddaf2-0d41-42b8-a262-4e384e865276.png)

**Comment by reynoldsnlp** [comment]
The `Save` button is having the same issue.
