### ISSUE TITLE
Hard coded values

### ISSUE THREAD

**Issue by ChristianHall131** [BYU-ODH/yvideo-client#493]
In the video editor and other editors, there are some hard coded values in the logic based on css that mess things up.

**Comment by dallan21** [comment]
@ChristianHall131 Do you have any examples of things that are being messed up so that I  can start looking at that?

**Comment by ChristianHall131** [comment]
one example is around line 406 in the video editor where it says (y-86). It is hard coded to account for the height of the navbar
