### ISSUE TITLE
Public Collections

### ISSUE THREAD

**Issue by esdraszx** [BYU-ODH/yvideo-client#50]
We need to have some collections available publicly. Add two features

1) On the Log In screen, add a button to `View public collections.`
2) On the student’s collections page, add a button to `Add a public collection.`

Public collections can be viewed by any person with or without a CAS user.
Only Instructors can create these collections, and only Lab assistants can add resources for them.

**Comment by reynoldsnlp** [comment]
I just realized that we need two different kinds of public collections. Some collections should be accessible by literally anyone, and some collections should be accessible to only BYU students/faculty/staff.

**Comment by esdraszx** [comment]
Submitted first draft of public collections with PR #113

**Comment by youthrich40** [comment]
enhancement of public collection and search public collection
0337e3ef14c444fb8d58e61badffc8f35e58f3ae
48e4c14d5900e1360fc6117b8384ab5435859739
6381e51523c0fae25f25392909f245d5577328c2
0cd5b4596176998edf556cd7ddad8c9102e35370
e7a8f24b4589f8255e8360f9a105bc02fb6ade12
78f159d019e4fc40ec6a5ee0a727deccffbd9071
af734a6d6777e43b6b0bd5d4cab968f93f675007
68ff54a5ecf2981f4a4d4805691eccf1445e9777
6c75b4791e1f7c35ef6892f854da888dc7061d1d
d7a7328c011ebe09be4ab57fb7e254c8c64c5856
0bb69bcbe7e990297aa3c67afb3ef71cb6d35680

**Comment by youthrich40** [comment]
- Students can add public collection but cannot remove public collection

**Comment by youthrich40** [comment]
bug fixed and performance improved
