### ISSUE TITLE
Add support for subtitles

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#51]
This should probably be divided into several smaller issues. We need the following:

1. Allow uploading subtitles in a variety of formats, especially SRT and VTT (and maybe SBV?). I assume that there is a stable js library with the ability to parse these formats. The subtitles could be stored in the db in one of these formats, e.g. SRT, but perhaps storing them as json would be more efficient at load time?
2. Create an interface to edit subtitles in the track editor. One way to do this is to make a `Subtitles` track type, and when it is selected, the name, language, and all of the subtitles become editable in the right sidebar? We should discuss possible approaches to the UI.
3. Allow the instructor to specify which subtitles are available to students. There could be more than one.
4. Allow instructors to export subtitles in one of the formats (SRT, VTT, etc.)

One of our parent projects, Ayamel, did some pretty useful things with subtitles. We should definitely look at its features for inspiration. (CaptionAider)

**Comment by ChristianHall131** [comment]
commit bc72be70e83849a24a2b9677631ab86b5af31cd3
