### ISSUE TITLE
Alert for IOS and safari users

### ISSUE THREAD

**Issue by fzhao21** [BYU-ODH/yvideo-client#574]
- provide an alert box before the user login for Safari/ios users
- if safari
        - alert: video playback doesn’t work on safari, ~please use~ we recommend Chrome
	- div over the player: msg: video doesn’t work
- if IOS (iPhone, iPad) 
          - alert: video playback doesn’t work on the iOS system, please use ~Chrome~ a different device
	- div over the player: msg: video doesn’t work

**Comment by reynoldsnlp** [comment]
@fzhao21 note my edits to your comment above.
