### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by Aaron-M-Anderson** [BYU-ODH/yvideo-client#602]
This is still here. I thought this was gotten rid of. I found it on the production site, not on localhost or dev.
![image (1)](https://user-images.githubusercontent.com/43586612/186511190-d31ab3a1-62ec-430b-b222-6c0637e53b72.png)

**Comment by dallan21** [comment]
@Aaron-M-Anderson I  created an issue on the backend for this. I  will keep you updated on the fixes
