### ISSUE TITLE
When playing a clip, it would be nice to have the ability to switch to other clips.

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#625]
Maybe make all the clips display in the scrubber, with their name showing on hover, or something. This needs some discussion, but it feels like it could definitely be more user-friendly for professors who use this to show a number of clips during class.

Along the same lines, if you go back to the main page after being in the player, it would be nice if the previous state were preserved (i.e. if clips had been revealed for a particular film).

**Comment by dallan21** [comment]
This is within the player. 
Add a button for clips on the blue line (right side of the player). Right under the transcripts button. Make it so that when you click on it, it will replace the transcripts and list all the clips the video has.
