### ISSUE TITLE
Opening new tab (target: _blank) Removal

### ISSUE THREAD

**Issue by Aaron-M-Anderson** [BYU-ODH/yvideo-client#632]

**Comment by clsyan** [comment]
Hi @Aaron-M-Anderson ! Can i work on this issue? Can you elaborate more in the description?

**Comment by Aaron-M-Anderson** [comment]
@clsyan Yeah so to elaborate a bit more, we never want there to be a new tab that is opened up when a link is clicked or a part of the site is accessed, so we want to remove the target: _blank that we have in a few places. However, we've noticed that this causes some other issues to occur within the page because of state updating not happening correctly when the time isn't provided, which seems to work just fine when a new tab is opened up.

**Comment by clsyan** [comment]
@Aaron-M-Anderson What kind of server should i use in the `REACT_APP_YVIDEO_SERVER` env variable?

**Comment by Aaron-M-Anderson** [comment]
Hey @clsyan, upon further review of the setup of our project, we really appreciate your interest in getting involved in the project and helping out, but we must graciously decline your help. Your time would be better used getting involved with other projects. Once again, we appreciate it!
