### ISSUE TITLE
`Name` field on manage files modal is unnecessarily narrow

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#636]
Long names are cut off.

![image](https://user-images.githubusercontent.com/13379223/188764703-0ac60812-c299-44b2-aa1d-dcc8faf0462e.png)

**Comment by kvaithin** [comment]
Where can I view this modal? Only seeing options to meddle with collections.

**Comment by Aaron-M-Anderson** [comment]
Hey @kvaithin, we appreciate your interest in helping out with the project. However, we must decline your offer to aid us with this issue. The team that's working on the issues will be able to handle these problems well, and we'd like to keep what we're working on here contained to the employees here at the Office of Digital Humanities. We think you'll find your time better used helping out with a different project. We're very grateful for your interest in contributing!
