### ISSUE TITLE
With new Editor Changes comes CSS possible changes

### ISSUE THREAD

**Issue by Aaron-M-Anderson** [BYU-ODH/yvideo-client#637]
It needs to be looked at with the change to the size of the scrubber if now the scubber's progress color needs to change to a lighter color to be more appealing.

**Comment by jtabilot** [comment]
Hi @Aaron-M-Anderson!
Can you provied more info about this issue?

**Comment by Aaron-M-Anderson** [comment]
This isn't an issue anymore, I will close it because I think the bar looks fine.
