### ISSUE TITLE
On the Edit User Access page, change "Current Users" to "Guests (read-only)"

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#665]

**Comment by Vinitvh** [comment]
Hi, can I work on this?

**Comment by Aaron-M-Anderson** [comment]
Hey @Vinitvh, we appreciate your interest in helping out with the project. However, we must decline your offer to aid us with this issue. The team that's working on the issues will be able to handle these problems well, and we'd like to keep what we're working on here contained to the employees here at the Office of Digital Humanities. We think you'll find your time better used helping out with a different issue. We're very grateful for your interest in contributing!
