### ISSUE TITLE
Two small fixes on `Edit User Access` tab

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#667]
1. Change both instances of `Enter netID or name` to `Enter netID`.
2. The `Expired Content` heading should never be visible in `Edit User Access`, only in the `Content` tab.

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/13379223/190870639-cd24ecbc-88f1-4862-bcd9-2d732928a76c.png">

**Comment by Alcadeus0** [comment]
Hi, can i work on this issue?
