### ISSUE TITLE
Owner of collection cannot pull it from Archived area

### ISSUE THREAD

**Issue by ThCovenant** [BYU-ODH/yvideo-client#669]
Selecting a collection in Archive list results in blank screen

**Comment by Aaron-M-Anderson** [comment]
@ThCovenant, I'm not able to recreate this in my own environment:
1. Do you know what type of user your account is where this issue is occurring?
2. By selecting, you mean as soon as you click on it on the left-hand section that displays all the collection names?

**Comment by reynoldsnlp** [comment]
@Aaron-M-Anderson try it in Lab Assistant.
