### ISSUE TITLE
Annotations exported to external file cannot be imported into resource

### ISSUE THREAD

**Issue by ThCovenant** [BYU-ODH/yvideo-client#679]
Since annotations are collection specific, there is a need to be able to import annotations when a resource is shared across collections, in case the second party would like to avail themselves of those annotations and avoid re-creating them.

**Comment by reynoldsnlp** [comment]
We need two separate Export options. The current one should be called `IC Player format` and the new one should not transform any of the JSON and should be called `Y-video format`. When you click on `Export` you should be given a decision which format you want.

Add an `Import` button that will take a `Y-video format` JSON file and then give the user a choice to either merge it with any existing annotations or replace all existing annotations.

**Comment by jtabilot** [comment]
@reynoldsnlp I was thinking something like this, 
![image](https://user-images.githubusercontent.com/25238958/202573880-47a0d929-18e6-4a3a-a618-f5ead8cff112.png)
