### ISSUE TITLE
`403 Forbidden` on `read-all-access` endpoint 

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#740]
This might be a backend problem, but I am guessing that a local front-end change is actually the problem.

On production, the user `co2` cannot add a content to his collection (IHUM 280R) from Manage Collections (http://localhost:3000/manager/484fb8a4-5e4a-4538-ae2d-dc9e23f35b4b), because of a `403 Forbidden` status on the `read-all-access` endpoint. The backend has always had that endpoint limited to Lab Assistant+, so the Manage Collections page should not be accessing that endpoint anyway, I believe. It may not be necessary at all to do this look-before-you-leap check.

I can add the content from Lab Assistant Manager, so it is not a resource permission problem.

**Comment by reynoldsnlp** [comment]
```Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at _callee$ (CreateContentContainer.jsx:162:1)
    at tryCatch (regeneratorRuntime.js:86:1)
    at Generator._invoke (regeneratorRuntime.js:66:1)
    at Generator.next (regeneratorRuntime.js:117:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)```

**Comment by Aaron-M-Anderson** [comment]
https://github.com/BYU-ODH/y-video-back-end/pull/130
