### ISSUE TITLE
Annotations glitch

### ISSUE THREAD

**Issue by ThCovenant** [BYU-ODH/yvideo-client#750]
Professor wants a small portion of film to be viewed and so skips entire first hour and then entire end, excepting 3 minutes in middle.  Film starts at end of first skip, but at beginning of next skip, it jumps to beginning of entire film, which is contained in the first skip.

**Comment by Aaron-M-Anderson** [comment]
I don't exactly understand what this problem is saying, but I think this got fixed with PR #752
