### ISSUE TITLE
ManageCollection throws unique key warning

### ISSUE THREAD

**Issue by youthrich40** [BYU-ODH/yvideo-client#79]
It looks like ContentOverviewContainer has a unique key from item.id, however, it still throws a warning.

**Comment by esdraszx** [comment]
fixed this with branch/commit => transcript-view-admin/4c9af1497290a64a3ee42d8492f245ecb8b8f011
The fixed was to return a direct child of array.map instead of a jsx empty tab <></>. Now returns `<div key={index}"></div>`
