### ISSUE TITLE
Stray grey bar

### ISSUE THREAD

**Issue by ThCovenant** [BYU-ODH/yvideo-client#802]
Professor used Video Editor to skip some content in film.  Now a thin grey bar appears 1/3 from bottom of screen.  Film is Medianeras in Mac Wilson's Span 330 collection.

**Comment by Aaron-M-Anderson** [comment]
@ThCovenant Could you please provide a screenshot of this issue?

**Comment by ThCovenant** [comment]
Sure thing.  Here 'tis.
________________________________

**Comment by Aaron-M-Anderson** [comment]
@ThCovenant I'm sorry, maybe I'm missing it, but I don't see a screenshot anywhere

**Comment by Aaron-M-Anderson** [comment]
@ThCovenant I found what you're talking about, never mind.
