### ISSUE TITLE
Add event to track editor

### ISSUE THREAD

**Issue by esdraszx** [BYU-ODH/yvideo-client#83]
Currently events are added at the current time of the video based on the percentage time / duration. 

The new functionality needs to support adding an event in the track editor wherever the user wants it. But, the issue is that if the user tries to add an event while being zoomed out, the event will not go where the user wants it. We need to find a way to read where the user let go and find a percentage userEvent / layerWidth

**Comment by reynoldsnlp** [comment]
If we copy the Youtube editor, we may not use drag-and-drop in our interface at all.
