### ISSUE TITLE
Import button is broken?

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#863]
A user should be able to export annotations from Video Editor (Y-video flavor), and then import those same annotations to a different content in Video Editor.

@ThCovenant tried to do this, but it didn't work.

**Comment by fzhao21** [comment]
- import y video format modal
- yes -> replace all annotations
- no -> add to existing annotations

**Comment by fzhao21** [comment]
Add tooltip in export and import 
ex: save changes to enable export/import 

Change wording on confirmation modal:
ex: Do you want to delete the current annotations?
add cancel option
